### ISSUE TITLE
Question about "rec" output option

### ISSUE THREAD

**Issue by megies** [geodynamics/sw4#12]
Hi @andersp and others,

I was confused about mismatches in seismogram output (`rec ... variables=displacement`) and `h_mag` images, and I think I found my problem now.. I just wanted to get this confirmed, as I think this is not perfectly clear from the (otherwise very detailed and comprehensive) manual.

Am I correct in assuming that if I want ground velocity output using a gaussian source time function, I need to specify `rec ... variables=displacement` in the input file? From what I understand now, specifying `variables=velocity` causes a differentiation of the solver quantity, which will cause output to actually be acceleration for a gaussian STF?

This is not perfectly clear in the manual, I think in the "10.5.1 rec (or sac) [optional]" section this behavior should be clarified.. this had me confused for quite a while now and I need to rerun several of my simulations.

regards,
Tobias

---

**Edit**: Reading through all parts regarding receiver output, it's actually mentioned in the manual alright (in section 8.2):

```
By default, the rec command outputs the three components of the solution (the displacement).
The rec command can also output the time derivative of the solution (the velocity),
```
and a bit above that..

```
that physical meaning of the solution depends on the source time function. For example, if the
displacement corresponds to a GaussianInt source time function, the solution would hold the
corresponding velocity if the time function was changed to a Gaussian.
```

Still, I think it's pretty misleading to use the terms `displacement` and `velocity` in the `rec` output command.. even more so since the program could internally account for the used STF if a pre-defined STF is used..

**Comment by andersp** [comment]
Hi Tobias,
We have made an effort to discuss the relation between the time function and the units of the output from the rec command, and I am glad to hear you managed to figure it out on your own. The names of the keywords make sense as long as you remember that SW4 solves the wave equations in displacement formulation. The fact that the material properties are independent of time allows you to differentiate the whole system, resulting in the same set of equations for the time derivative of the displacement (particle velocity), if you also differentiate the time function with respect to time. In the end it is the units of the time function that determines the physical interpretation of the solution from SW4. 
I agree that the names of the keywords in the rec (sac) command could be improved and you should let us know if you have any suggestions. Perhaps some of the confusion will go away if you just omit the "variables=" keyword, because the default is "displacement". Then you only have to keep track of the units of your time function.
/Anders

**Comment by megies** [comment]
Thanks for the confirmation Anders. Like I said, in general the manual is really well written and makes it relatively easy to use SW4. Thanks for your efforts with the manual!

T
