### ISSUE TITLE
About SSI output

### ISSUE THREAD

**Issue by BFF-LEI-Lei** [geodynamics/sw4#178]
Hi，
I tried to output results by SSI and REC simultaneously and opened the SSI.h5 file by hdf5view.In the SSI.h5 file, I thought the data was velocity-history at first by their name. However, I found they were displacement -history after the comparison between SSI and REC results just like below:
1)Content of the SSI file shows it just contains VEL
![image](https://user-images.githubusercontent.com/65699368/227533785-27a38387-4270-4efd-af80-e58b237d0821.png)
2)The SSI output data 
![image](https://user-images.githubusercontent.com/65699368/227537159-0450b2d0-9043-4d5e-a730-9bb5ad68d326.png)
3)The REC output  data
![image](https://user-images.githubusercontent.com/65699368/227537256-d2604571-177f-446c-bdad-3ce8eab22751.png)

And I hope the SSI file can contain displacement, velocity, and acceleration time history, and each point's XYZ information.

Thanks!

**Comment by houjun** [comment]
Hi @BFF-LEI-Lei, the ssioutput option writes out the default variable based on the source/time function used, we typically use time functions that produce velocity data for both rec/rechdf5 and ssioutput, and we just named the ssioutput dataset name to be velocity, but it could actually be displacement values if your time function is different. I'll add some description in the UserGuide. Thanks for pointing this out.

Also, since ssioutput file can be huge (TBs) for big simulations, we do not plan to include the other two variables that can be computed from velocity (or displacement).

**Comment by BFF-LEI-Lei** [comment]
Thank you for your reply！
The content you mentioned appears in Chapter 4 of the UserGuide. I should pay more attention to the contents of the manual.
Finally, I would like to suggest that you can provide the related position in the SSI file for each point cause it won't add a huge additional burden.
Thanks again for your attention！
