### ISSUE TITLE
USGS station output txt file has incorrect timestamps on restart

### ISSUE THREAD

**Issue by drhansj** [geodynamics/sw4#24]
On developer branch HEAD, doing LOH.1 test, if you look at the USGS station output file it doesn't have the correct time stamp when restarting from a checkpoint file.

**Comment by drhansj** [comment]
Found the issue @andersp - because checkpoint is read inside EW::solve (line 270), it is after the a_TimeSeries are initialized (line 114). One solution is to move initialization after checkpoint; another is to add a method to re-allocate after we realize we have a checkpoint restart. Let me know if you have a preference.

**Comment by andersp** [comment]
The easiest might be to add a method to the timeSeries class that allows the starting time to be set.

Sent from my iPhone

On Mar 9, 2018, at 2:47 PM, Hans Johansen <notifications@github.com<mailto:notifications@github.com>> wrote:


Found the issue @andersp<https://github.com/andersp> - because checkpoint is read inside EW::solve (line 270), it is after the a_TimeSeries are initialized (line 114). One solution is to move initialization after checkpoint; another is to add a method to re-allocate after we realize we have a checkpoint restart. Let me know if you have a preference.

**Comment by bjorn2** [comment]
Station output together with checkpoints is not yet implemented, you should not expect it to work.
