### ISSUE TITLE
Topography issues

### ISSUE THREAD

**Issue by ar4** [geodynamics/sw4#38]
Page 33 of the user's guide (Chapter 5, Topography) recommends

> zmax >= -e_min + 3(e_max - e_min)

but on page 80 (section 11.4), the recommendation is only 2 times the topography range.

It appears that the 3 times recommendation is warranted, as this example fails:
```
grid nx=70 ny=70 nz=40 h=5.0
time steps=1
source x=175.0 y=175.0 depth=0.1 freq=10 type=Ricker fz=1.0
block vp=1500.0 vs=1000.0 rho=2500.0
topography input=gaussian zmax=50.0 gaussianAmp=20.0 gaussianXc=175.0 gaussianYc=175.0 gaussianLx=50.0 gaussianLy=50.0
```
unless zmax is increased (60.0 works).

Another topography issue is that if I replace the topography line above with
`topography input=cartesian file=topo.in zmax=150.0`
where topo.in contains a topography that is constant everywhere, SW4 runs successfully when this elevation constant is -90m, but fails when it is -100m. The error message is:

> Fatal input error: Density= -1.00000000e+00 in grid g= 1 at point  (-1,34,-1) 
> Fatal input error: Density= -1.00000000e+00 in grid g= 1 at point  (-1,-1,-1)

**Comment by bjorn2** [comment]
The failure occurs because the default limits in the z-direction for the block command are not set large enough when the topography is extreme. This is a bug, that is easy to fix, but is not checked it in yet. As a temporary fix, you can explicitly set the upper limit to the block command large enough. This works in the given example:
block vp=1500.0 vs=1000.0 rho=2500.0 z1=-100
